dependencies:
  # -<organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
network:
  defualt: development    
  goerli:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    verify: True
   mainnet-fork:
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"  #这里改成chainlinkdoc上面的对应的测试的地址就好了  
    verify: False
  development: 
     verify: False
  ganache-local:
    verify: False
  rinkeby:
  kovan:
  mainnet:

wallets:
  from_key: ${PRIVATE_KEY}